<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Quotation {{ $quotation->document_number }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }

        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .details-table td {
            padding: 5px;
            vertical-align: top;
        }

        .items-table {
            width: 100%;
            border-collapse: collapse;
        }

        .items-table th,
        .items-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .items-table th {
            background-color: #f8f9fa;
        }

        .text-end {
            text-align: right;
        }

        .fw-bold {
            font-weight: bold;
        }

        .mb-4 {
            margin-bottom: 1.5rem;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>{{ __('messages.quotation') }}</h2>
        <p>{{ $quotation->document_number }}</p>
    </div>

    <table class="details-table">
        <tr>
            <td style="width: 50%;">
                <h3 class="fw-bold">{{ __('messages.customer_details') }}</h3>
                <p>{{ $quotation->customer->name }}<br>
                    {{ $quotation->customer->address }}<br>
                    {{ $quotation->customer->phone }}<br>
                    {{ $quotation->customer->email }}</p>
            </td>
            <td style="width: 50%; text-align: right;">
                <h3 class="fw-bold">{{ __('messages.quotation_details') }}</h3>
                <p><strong>{{ __('messages.date') }}:</strong> {{ $quotation->quotation_date->format('Y-m-d') }}<br>
                    <strong>{{ __('messages.expiry_date') }}:</strong>
                    {{ $quotation->expiry_date->format('Y-m-d') }}<br>
                    <strong>{{ __('messages.status') }}:</strong> {{ ucfirst($quotation->status) }}
                </p>
            </td>
        </tr>
    </table>

    <table class="items-table mb-4">
        <thead>
            <tr>
                <th>{{ __('messages.product') }}</th>
                <th class="text-end">{{ __('messages.quantity') }}</th>
                <th class="text-end">{{ __('messages.unit_price') }}</th>
                <th class="text-end">{{ __('messages.tax') }} (%)</th>
                <th class="text-end">{{ __('messages.tax_amount') }}</th>
                <th class="text-end">{{ __('messages.net_amount') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($quotation->items as $item)
                <tr>
                    <td>{{ $item->product ? $item->product->name_en : '-' }}</td>
                    <td class="text-end">{{ number_format($item->quantity, 2) }}</td>
                    <td class="text-end">{{ number_format($item->unit_price, 2) }}</td>
                    <td class="text-end">{{ number_format($item->tax_rate, 2) }}</td>
                    <td class="text-end">{{ number_format($item->tax_amount, 2) }}</td>
                    <td class="text-end">{{ number_format($item->net_amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" class="text-end fw-bold">{{ __('messages.subtotal') }}</td>
                <td class="text-end fw-bold">{{ number_format($quotation->subtotal, 2) }}</td>
            </tr>
            <tr>
                <td colspan="5" class="text-end fw-bold">{{ __('messages.tax_amount') }}</td>
                <td class="text-end fw-bold">{{ number_format($quotation->tax_amount, 2) }}</td>
            </tr>
            <tr>
                <td colspan="5" class="text-end fw-bold">{{ __('messages.grand_total') }}</td>
                <td class="text-end fw-bold">{{ number_format($quotation->total_amount, 2) }}</td>
            </tr>
        </tfoot>
    </table>

    @if($quotation->terms_conditions)
        <div class="mb-4">
            <h4 class="fw-bold">{{ __('messages.terms_conditions') }}</h4>
            <p>{{ $quotation->terms_conditions }}</p>
        </div>
    @endif

    @if($quotation->notes)
        <div class="mb-4">
            <h4 class="fw-bold">{{ __('messages.notes') }}</h4>
            <p>{{ $quotation->notes }}</p>
        </div>
    @endif

    <div class="footer">
        <p>Generated by Aurex ERP on {{ date('Y-m-d H:i:s') }}</p>
    </div>
</body>

</html>